# Sparse projection
proj:
    filename: /home/luca/alice/Ds_reso/AnalysisResults_Ds1Trigger_noCDau.root
    dirname:   hf-task-reso
    histname: hSparseMl
    ptAxis: 0
    ptLims: [0.,1., 2.,3., 4.,5., 6., 12, 24.]
    massAxis: 3
    masslims: [2.5, 3.09]

fit:
    filename: 
    histname:
    pdgId: 10433 # options [10433 = Ds1, 435 = Ds2Star, 666=XcStar]
    fitLims: [2.51, 2.95]
    plotLims: [2.5, 2.7]
    deltaMass: false
