input: # files to use, set FD to null for binary classification
    prompt: /home/luca/HF_data/TrainingBDTapass7/filtered/Prompt_Dplus_pprun3_LHC24g5_pT_0_100.parquet.gzip
    FD: /home/luca/HF_data/TrainingBDTapass7/filtered/FD_Dplus_pprun3_LHC24g5_pT_0_100.parquet.gzip
    data: /home/luca/HF_data/TrainingBDTapass7/filtered/Data_Dplus_pprun3_LHC22pass7_pT_0_100.parquet.gzip
    treename: null

output:
    leg_labels: # legend labels, keep the right number of classes
        Bkg: Background
        Prompt: Prompt D$^+$
        FD: Feed-down D$^+$
    out_labels: # output labels, keep the right number of classes
        Bkg: Bkg
        Prompt: Prompt
        FD: FD
    dir: '/home/luca/hd_data/Physics/DsReso_run3/outputML/apass7Dplus/all' # output dir

pt_ranges: # ranges in pt to split the data in the ml training and testing
    min: [0, 1, 2, 3, 5, 7, 10, 15, 20] # list
    max: [1, 2, 3, 5, 7, 10, 15, 20, 50] # list

data_prep:
    filt_bkg_mass: (fM < 1.8 or fM > 1.95) and fM < 2.05 # pandas query to select bkg candidates
    dataset_opt: equal  # change how the dataset is built, options available: 'equal', 'max_signal'
                        # 'equal' -> same number of prompt/FD/bkg (not using all the signal available)
                        # 'max_signal' -> try to use all the signal (prompt and FD) + add n_bkg = 2 * (n_prompt + n_FD)
    bkg_mult: [1., 1., 1., 1., 1., 1., 1., 1., 1.] # list of multipliers for (nPrompt + nFD) used to determine nCandBkg in the 'max_signal' option
    seed_split: 42 # seed used for train_test_split(...)
    test_fraction: 1 # fraction of data used for test set and efficiencies     

ml:
    raw_output: False # use raw_output (True) of probability (False) as output of the model
    roc_auc_average: 'macro' # 'macro' or 'weighted'
    roc_auc_approach: 'ovo'  # 'ovo' or 'ovr'
    training_columns: ['fDecayLength', 'fDecayLengthXY', 'fCpa', 'fCpaXY', 
                        'fDecayLengthXYNormalised', 'fChi2PCA', 'fMaxNormalisedDeltaIP',
                        'fNSigTpcTofPi0', 'fNSigTpcTofKa0', 'fNSigTpcTofPi1', 'fNSigTpcTofKa1', 'fNSigTpcTofPi2', 'fNSigTpcTofKa2'] 
                       # list of training variables
#-------------------------------------------FROM STEFANO------------------------------------------#
    # hyper_par: [{'max_depth':3, 'learning_rate':0.0238, 'n_estimators':1028, 'min_child_weight':5, 'n_jobs':16, 'tree_method':hist},
    #             {'max_depth':3, 'learning_rate':0.0238, 'n_estimators':1028, 'min_child_weight':5, 'n_jobs':16, 'tree_method':hist},
    #             {'max_depth':4, 'learning_rate':0.0210, 'n_estimators':1282, 'min_child_weight':5, 'n_jobs':16, 'tree_method':hist},
    #             {'max_depth':4, 'learning_rate':0.0210, 'n_estimators':1282, 'min_child_weight':5, 'n_jobs':16, 'tree_method':hist},
    #             {'max_depth':4, 'learning_rate':0.0210, 'n_estimators':1282, 'min_child_weight':5, 'n_jobs':16, 'tree_method':hist},
    #             {'max_depth':4, 'learning_rate':0.0210, 'n_estimators':1282, 'min_child_weight':5, 'n_jobs':16, 'tree_method':hist},
    #             {'max_depth':4, 'learning_rate':0.0210, 'n_estimators':1282, 'min_child_weight':5, 'n_jobs':16, 'tree_method':hist},
    #             {'max_depth':3, 'learning_rate':0.0283, 'n_estimators':1067, 'min_child_weight':5, 'n_jobs':16, 'tree_method':hist},
    #             {'max_depth':3, 'learning_rate':0.0283, 'n_estimators':1067, 'min_child_weight':5, 'n_jobs':16, 'tree_method':hist}]
    #             # list of dicts of hyperparameters (one for each pT bin)

    # hyper_par_opt:
    #   do_hyp_opt: True # whether to do the parameter optimization
    #   njobs: 8 # number of parallel jobs used in hyper-parameter optimization, -1. to use all
    #   nfolds: 5 # number of folds used in cross validation
    #   initpoints: 10 # steps of random exploration you want to perform
    #   ntrials: 8 # steps for bayesian optimization
    #   timeout: null
    #   direction : "maximize"
    #   bayes_opt_config: {'max_depth': !!python/tuple [2, 3], 
    #                     'learning_rate': !!python/tuple [0.01, 0.05],
    #                     'n_estimators': !!python/tuple [500, 1300],
    #                     'min_child_weight': !!python/tuple [1, 10],
    #                     'subsample': !!python/tuple [0.8, 1.], 
    #                     'colsample_bytree': !!python/tuple [0.8, 1.],
    #                     'lambda': !!python/tuple [0., 0.001]}
    #                     # configuration dictionary for optimize_params_bayes()
#---------------------------------------------FROM CHINU------------------------------------------#
    hyper_par: [
        {'max_depth':4, 'learning_rate':0.029, 'n_estimators':500, 'min_child_weight':2.7, 'subsample':0.90, 'colsample_bytree':0.97, 'n_jobs':1, 'tree_method':hist, 'lambda':0.01},
        {'max_depth':4, 'learning_rate':0.029, 'n_estimators':500, 'min_child_weight':2.7, 'subsample':0.90, 'colsample_bytree':0.97, 'n_jobs':1, 'tree_method':hist, 'lambda':0.01},
        {'max_depth':4, 'learning_rate':0.029, 'n_estimators':500, 'min_child_weight':2.7, 'subsample':0.90, 'colsample_bytree':0.97, 'n_jobs':1, 'tree_method':hist, 'lambda':0.01},
        {'max_depth':4, 'learning_rate':0.029, 'n_estimators':500, 'min_child_weight':2.7, 'subsample':0.90, 'colsample_bytree':0.97, 'n_jobs':1, 'tree_method':hist, 'lambda':0.01},
        {'max_depth':4, 'learning_rate':0.029, 'n_estimators':500, 'min_child_weight':2.7, 'subsample':0.90, 'colsample_bytree':0.97, 'n_jobs':1, 'tree_method':hist, 'lambda':0.01},
        {'max_depth':4, 'learning_rate':0.029, 'n_estimators':500, 'min_child_weight':2.7, 'subsample':0.90, 'colsample_bytree':0.97, 'n_jobs':1, 'tree_method':hist, 'lambda':0.01},
        {'max_depth':4, 'learning_rate':0.029, 'n_estimators':500, 'min_child_weight':2.7, 'subsample':0.90, 'colsample_bytree':0.97, 'n_jobs':1, 'tree_method':hist, 'lambda':0.01},
        {'max_depth':4, 'learning_rate':0.029, 'n_estimators':500, 'min_child_weight':2.7, 'subsample':0.90, 'colsample_bytree':0.97, 'n_jobs':1, 'tree_method':hist, 'lambda':0.01},
        {'max_depth':4, 'learning_rate':0.029, 'n_estimators':500, 'min_child_weight':2.7, 'subsample':0.90, 'colsample_bytree':0.97, 'n_jobs':1, 'tree_method':hist, 'lambda':0.01}
    ]
               # list of dicts of hyperparameters (one for each pT bin)

    hyper_par_opt:
      do_hyp_opt: True # whether to do the parameter optimization
      njobs: 12 # number of parallel jobs used in hyper-parameter optimization, -1. to use all
      nfolds: 5 # number of folds used in cross validation
      initpoints: 10 # steps of random exploration you want to perform
      n_trials: 15 # steps for bayesian optimization
      timeout: null
      opt_tuna_config: {'max_depth': !!python/tuple [1, 4], 
                        'learning_rate': !!python/tuple [0.01, 0.1],
                        'n_estimators': !!python/tuple [300, 1500], 
                        'min_child_weight': !!python/tuple [1, 10],
                        'subsample': !!python/tuple [0.8, 1.], 
                        'colsample_bytree': !!python/tuple [0.8, 1.],
                        'lambda': !!python/tuple [0., 0.001]}
                        # configuration dictionary for optimize_params_bayes()
    
    saved_models: [/home/luca/hd_data/Physics/DsReso_run3/outputML/apass7Dplus/all/pt0_1/ModelHandler_pT_0_1.pickle, 
                   /home/luca/hd_data/Physics/DsReso_run3/outputML/apass7Dplus/all/pt1_2/ModelHandler_pT_1_2.pickle, 
                   /home/luca/hd_data/Physics/DsReso_run3/outputML/apass7Dplus/all/pt2_3/ModelHandler_pT_2_3.pickle, 
                   /home/luca/hd_data/Physics/DsReso_run3/outputML/apass7Dplus/all/pt3_5/ModelHandler_pT_3_5.pickle,
                   /home/luca/hd_data/Physics/DsReso_run3/outputML/apass7Dplus/all/pt5_7/ModelHandler_pT_5_7.pickle,  
                   /home/luca/hd_data/Physics/DsReso_run3/outputML/apass7Dplus/all/pt7_10/ModelHandler_pT_7_10.pickle, 
                   /home/luca/hd_data/Physics/DsReso_run3/outputML/apass7Dplus/all/pt10_15/ModelHandler_pT_10_15.pickle,
                   /home/luca/hd_data/Physics/DsReso_run3/outputML/apass7Dplus/all/pt15_20/ModelHandler_pT_15_20.pickle,
                   /home/luca/hd_data/Physics/DsReso_run3/outputML/apass7Dplus/all/pt20_50/ModelHandler_pT_20_50.pickle] # list of saved ModelHandler (path+file), compatible with the pt bins # list of saved ModelHandler (path+file), compatible with the pt bins

plots:
    plotting_columns: ['fM', 'fPt', 
                        'fDecayLength', 'fDecayLengthXY', 'fCpa', 'fCpaXY', 
                        'fDecayLengthXYNormalised', 'fChi2PCA', 'fMaxNormalisedDeltaIP',
                        'fNSigTpcTofPi0', 'fNSigTpcTofKa0', 'fNSigTpcTofPi1', 'fNSigTpcTofKa1', 'fNSigTpcTofPi2', 'fNSigTpcTofKa2'
                        ] 
                       # list of variables to plot
    train_test_log: True # use log scale for plots of train and test distributions
  
appl: 
    column_to_save_list: ['fM', 'fPt'] # list of variables saved in the dataframes with the applied models

standalone_appl:
    treename: null # null if using parquet
    inputs: [] # list of parquet files for the model application
    output_names: [] # names for the outputs (one for each file)
    output_dir: /home/luca/hd_data/Physics/DsReso_run3/outputML/apass7Dplus/all/apply_apass7 # output directory

conversion:
    output_folder : '/home/luca/hd_data/Physics/DsReso_run3/outputML/apass7Dplus/all/converted/'