#config for significance optimization on data
#projection
inputfile: /home/lagliett/outputML/data/AnalysisResults_LHC22pass7small_TaskDstar_MlNoNorm.root
dirname: task-polarisation-charm-hadrons
sparsename: hHelicity
projfile: /home/lagliett/outputML/data/Proj_LHC22pass7small_TaskDstar_MlNoNorm.root
outputfolder: /home/lagliett/outputML/plots/
pdgId: 413
cutvars: 
  pt:
    min:  [ 1.0, 2.0, 3.0, 5.0, 7.0, 10., 15., 20.] 
    max:  [ 2.0, 3.0, 5.0, 7.0, 10., 15., 20., 50.]
    axisnum: 1  
  bkgBDT:
    min:  [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  
    max:  [ 0.2, 0.5, 1, 1, 1, 1, 1, 1]
    axisnum: 6
  massFitRange:
    min : [0.141, 0.141, 0.141, 0.141, 0.141, 0.141, 0.141, 0.141]
    max : [0.152, 0.152, 0.152, 0.152, 0.152, 0.152, 0.152, 0.152]
rebin:
  [ 1, 1, 1, 1, 1, 1, 1, 1]
mass:
  min : 0.14
  max : 0.155 
nsteps: 20