channel: Dplus # options [D0, Ds, Dplus, Dstar]

infile:
    isMC: true
    filename: [/home/luca/HF_data/TrainingBDTapass7/AO2D_DplusTree_LHC24g5.root ]
    dirname:   # look for every DF
    treename: O2hfcanddplite

outfile:
    dirpath: /home/luca/HF_data/TrainingBDTapass7/filtered/
    suffix: _Dplus_pprun3_LHC24g5
    treename: O2hfcanddplite
    
skimming:
    pt:
        min: [0]
        max: [100]
    preselections:   ["fNSigTpcTofPi0 < 7500 & fNSigTpcTofPi1 < 7500 & fNSigTpcTofPi2 < 7500 & fNSigTpcTofKa0 < 7500 & fNSigTpcTofKa1 < 7500 & fNSigTpcTofKa2 < 7500"] # null if you don't want to apply preselections

    colstokeep: [  'fDecayLength', 'fDecayLengthXY', 'fCpa', 'fCpaXY', 
                'fImpactParameter0', 'fImpactParameter1', 'fImpactParameter2',
                'fImpactParameterZ0', 'fImpactParameterZ1', 'fImpactParameterZ2',
                'fDecayLengthNormalised', 'fDecayLengthXYNormalised', 'fChi2PCA', 'fMaxNormalisedDeltaIP',
                'fNSigTpcPi0', 'fNSigTpcKa0', 'fNSigTpcPi1', 'fNSigTpcKa1', 'fNSigTpcPi2', 'fNSigTpcKa2',
                'fNSigTofPi0', 'fNSigTofKa0', 'fNSigTofPi1', 'fNSigTofKa1', 'fNSigTofPi2', 'fNSigTofKa2',
                'fNSigTpcTofPi0', 'fNSigTpcTofKa0', 'fNSigTpcTofPi1', 'fNSigTpcTofKa1', 'fNSigTpcTofPi2', 'fNSigTpcTofKa2',
                'fM', 'fPt' ] 
missingvalues: # values in dataframe to be replaced with NaN (only possible with python script)
    enable: 0
    toreplace:
        nsigTOF_Pi_0: -999.
        nsigTOF_K_0: -999.
        nsigTOF_Pi_1: -999.
        nsigTOF_K_1: -999.
        nsigTOF_Pi_2: -999.
        nsigTOF_K_2: -999.